<h1><font color="blue">DataFrame 연산하기</font></h1>

<h2><font color="red">다중 열(column) 선택</font></h2>

<h4><font color="green">DataFrame 요약 정보 확인</font></h4>

<h6><font color="BlueViolet">DataFrame 기초 정보 확인</font></h6>

In [5]:
import pandas as pd

In [6]:
payment = pd.read_csv('./../data/payment02.csv', encoding='CP949')
print('payment 정보 학인하기')
print(payment.info())

payment 정보 학인하기
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사원명     6 non-null      object
 1   출장지역    6 non-null      object
 2   출장기간    6 non-null      int64
 3   부서      6 non-null      object
 4   성별      6 non-null      object
 5   교통비     6 non-null      int64
 6   식비      6 non-null      int64
 7   숙박비     6 non-null      int64
 8   부대비용    6 non-null      int64
dtypes: int64(5), object(4)
memory usage: 560.0+ bytes
None

In [7]:
print(payment.index)

RangeIndex(start=0, stop=6, step=1)

In [8]:
print(payment.columns)

Index(['사원명', '출장지역', '출장기간', '부서', '성별', '교통비', '식비', '숙박비', '부대비용'], dtype='object')

In [9]:
print(payment.dtypes)

사원명     object
출장지역    object
출장기간     int64
부서      object
성별      object
교통비      int64
식비       int64
숙박비      int64
부대비용     int64
dtype: object

<h6><font color="BlueViolet">다중 열 선택하기</font></h6>

In [10]:
search_column = ['사원명', '부서', '성별']
payment_data = payment[search_column]
result = payment_data.head()
result

   사원명   부서  성별
0  강찬혁  영업부  남자
1  이성진  구매부  남자
2  이순철  전산부  남자
3  신유석  영업부  여자
4  선진희  총무부  여자

In [11]:
result = payment[['사원명']]
result

   사원명
0  강찬혁
1  이성진
2  이순철
3  신유석
4  선진희
5  유지혜

<h2><font color="red">메소드를 사용한 열 선택</font></h2>

<h4><font color="green">실습 파일 읽기</font></h4>

<h6><font color="BlueViolet">DataFrame 데이터 타입 확인하기</font></h6>

In [12]:
payment = pd.read_csv('./../data/payment02.csv', index_col='사원명', \
                      encoding='CP949')
payment.dtypes.to_frame().T

     출장지역   출장기간      부서      성별    교통비     식비    숙박비   부대비용
0  object  int64  object  object  int64  int64  int64  int64

In [13]:
payment

    출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
사원명
강찬혁   부산     3  영업부  남자  3000  1000  1000   100
이성진   대구     5  구매부  남자  5000  6000  2000   200
이순철   부산     4  전산부  남자  6000  3000  3000   400
신유석   대구     5  영업부  여자  1000  5000  6000   600
선진희   서울     6  총무부  여자  5000  3000  1000   500
유지혜   대구     5  전산부  여자  3000  3000  2000   300

<h6><font color="BlueViolet">개발자 지정 데이터 타입의 열만 선택하기</font></h6>

In [14]:
result = payment.select_dtypes(include=['int64'])
result

     출장기간   교통비    식비   숙박비  부대비용
사원명
강찬혁     3  3000  1000  1000   100
이성진     5  5000  6000  2000   200
이순철     4  6000  3000  3000   400
신유석     5  1000  5000  6000   600
선진희     6  5000  3000  1000   500
유지혜     5  3000  3000  2000   300

In [15]:
result = payment.select_dtypes(include=['number'])
result

     출장기간   교통비    식비   숙박비  부대비용
사원명
강찬혁     3  3000  1000  1000   100
이성진     5  5000  6000  2000   200
이순철     4  6000  3000  3000   400
신유석     5  1000  5000  6000   600
선진희     6  5000  3000  1000   500
유지혜     5  3000  3000  2000   300

<h6><font color="BlueViolet">컬럼 필터링하기</font></h6>

In [16]:
# 컬럼 이름에 '비'라는 글자가 들어 있으면 추출합니다.
result = payment.filter(like='비').head() 
result

      교통비    식비   숙박비  부대비용
사원명
강찬혁  3000  1000  1000   100
이성진  5000  6000  2000   200
이순철  6000  3000  3000   400
신유석  1000  5000  6000   600
선진희  5000  3000  1000   500

In [17]:
# regex : 정규 표현식(regular expression)
# 꺽쇠(^) 기호는 '~으로 시작하는', 달러($) 기호는 '~으로 끝나는'의 의미
result = payment.filter(regex='비$').head() 
result

      교통비    식비   숙박비
사원명
강찬혁  3000  1000  1000
이성진  5000  6000  2000
이순철  6000  3000  3000
신유석  1000  5000  6000
선진희  5000  3000  1000

In [18]:
# 정규 표현식 : '부'또는 '박'자를 포함하고 있는~~
payment.filter(regex='(부|박)').head()

      부서   숙박비  부대비용
사원명
강찬혁  영업부  1000   100
이성진  구매부  2000   200
이순철  전산부  3000   400
신유석  영업부  6000   600
선진희  총무부  1000   500

In [19]:
result = payment.filter(items=['식비', '교통비']).head()
result

       식비   교통비
사원명
강찬혁  1000  3000
이성진  6000  5000
이순철  3000  6000
신유석  5000  1000
선진희  3000  5000

<h2><font color="red">컬럼 이름 재배치하기</font></h2>

<h4><font color="green">실습 파일 읽기</font></h4>

<h6><font color="BlueViolet">DataFrame 내용 확인</font></h6>

In [20]:
payment = pd.read_csv('./../data/payment02.csv', encoding='CP949')
payment

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
0  강찬혁   부산     3  영업부  남자  3000  1000  1000   100
1  이성진   대구     5  구매부  남자  5000  6000  2000   200
2  이순철   부산     4  전산부  남자  6000  3000  3000   400
3  신유석   대구     5  영업부  여자  1000  5000  6000   600
4  선진희   서울     6  총무부  여자  5000  3000  1000   500
5  유지혜   대구     5  전산부  여자  3000  3000  2000   300

In [21]:
print(payment.columns)

Index(['사원명', '출장지역', '출장기간', '부서', '성별', '교통비', '식비', '숙박비', '부대비용'], dtype='object')

<h4><font color="green">컬럼 재배치 하기</font></h4>

<h6><font color="BlueViolet">재배치를 위한 list 만들기</font></h6>

In [22]:
column01 = ['사원명', '출장지역', '부서', '성별']
column02 = ['교통비', '숙박비', '식비', '부대비용', '출장기간']
myordering = column01 + column02
print('컬럼 재배치 현황 : \n' + str(myordering))

컬럼 재배치 현황 :
['사원명', '출장지역', '부서', '성별', '교통비', '숙박비', '식비', '부대비용', '출장기간']

In [23]:
result = set(payment.columns) == set(myordering)
print('최초 컬럼 정보와 동일한가 ? ' +str(result))

최초 컬럼 정보와 동일한가 ? True

In [24]:
paymentnew = payment[myordering]
paymentnew

   사원명 출장지역   부서  성별   교통비   숙박비    식비  부대비용  출장기간
0  강찬혁   부산  영업부  남자  3000  1000  1000   100     3
1  이성진   대구  구매부  남자  5000  2000  6000   200     5
2  이순철   부산  전산부  남자  6000  3000  3000   400     4
3  신유석   대구  영업부  여자  1000  6000  5000   600     5
4  선진희   서울  총무부  여자  5000  1000  3000   500     6
5  유지혜   대구  전산부  여자  3000  2000  3000   300     5

<h2><font color="red">기초 통계 요약 정보 확인</font></h2>

<h4><font color="green">통계 요약 정보 </font></h4>

<h6><font color="BlueViolet">속성을 이용한 행과 열의 기본 정보</font></h6>

In [25]:
print('payment.size : ' + str(payment.size))# 전체 요소의 갯수
print('payment.shape : ' + str(payment.shape)) # 형상 확인
print('행수 : ' + str(payment.shape[0])) 
print('열수 : ' + str(payment.shape[1])) 
print('payment.ndim : ' + str(payment.ndim)) # 차원 수
print('len(payment) : ' + str(len(payment)))# 행 개수

payment.size : 54
payment.shape : (6, 9)
행수 : 6
열수 : 9
payment.ndim : 2
len(payment) : 6

In [26]:
print('payment.count()') 
payment.count().to_frame().T

payment.count()

   사원명  출장지역  출장기간  부서  성별  교통비  식비  숙박비  부대비용
0    6     6     6   6   6    6   6    6     6

<h6><font color="BlueViolet">통계 정보 확인하기</font></h6>

In [27]:
# 기본 값으로 숫자형 데이터의 간략한 통계치 정보를 보여 줍니다.
payment.describe().T

      count         mean          std     min      25%     50%     75%     max
출장기간    6.0     4.666667     1.032796     3.0     4.25     5.0     5.0     6.0
교통비     6.0  3833.333333  1834.847859  1000.0  3000.00  4000.0  5000.0  6000.0
식비      6.0  3500.000000  1760.681686  1000.0  3000.00  3000.0  4500.0  6000.0
숙박비     6.0  2500.000000  1870.828693  1000.0  1250.00  2000.0  2750.0  6000.0
부대비용    6.0   350.000000   187.082869   100.0   225.00   350.0   475.0   600.0

In [28]:
payment.describe(include='number').T

      count         mean          std     min      25%     50%     75%     max
출장기간    6.0     4.666667     1.032796     3.0     4.25     5.0     5.0     6.0
교통비     6.0  3833.333333  1834.847859  1000.0  3000.00  4000.0  5000.0  6000.0
식비      6.0  3500.000000  1760.681686  1000.0  3000.00  3000.0  4500.0  6000.0
숙박비     6.0  2500.000000  1870.828693  1000.0  1250.00  2000.0  2750.0  6000.0
부대비용    6.0   350.000000   187.082869   100.0   225.00   350.0   475.0   600.0

In [29]:
payment.describe(include='all')

,사원명,출장지역,출장기간,부서,성별,교통비,식비,숙박비,부대비용
count,6,6,6.000000,6,6,6.000000,6.000000,6.000000,6.000000
unique,6,3,NaN,4,2,NaN,NaN,NaN,NaN
top,강찬혁,대구,NaN,영업부,남자,NaN,NaN,NaN,NaN
freq,1,3,NaN,2,3,NaN,NaN,NaN,NaN
mean,NaN,NaN,4.666667,NaN,NaN,3833.333333,3500.000000,2500.000000,350.000000
std,NaN,NaN,1.032796,NaN,NaN,1834.847859,1760.681686,1870.828693,187.082869
min,NaN,NaN,3.000000,NaN,NaN,1000.000000,1000.000000,1000.000000,100.000000
25%,NaN,NaN,4.250000,NaN,NaN,3000.000000,3000.000000,1250.000000,225.000000
50%,NaN,NaN,5.000000,NaN,NaN,4000.000000,3000.000000,2000.000000,350.000000
75%,NaN,NaN,5.000000,NaN,NaN,5000.000000,4500.000000,2750.000000,475.000000
max,NaN,NaN,6.000000,NaN,NaN,6000.000000,6000.000000,6000.000000,600.000000

In [30]:
payment.describe(include='object').T

     count unique  top freq
사원명      6      6  강찬혁    1
출장지역     6      3   대구    3
부서       6      4  영업부    2
성별       6      2   남자    3

In [31]:
mylist = [0.3 * idx for idx in range(1, 4)]

# percentiles 매개 변수를 이용하여 특정 지점의 백분위수를 확인할 수 있습니다.
paymentPect = payment.describe(include='number', percentiles=mylist).T
paymentPect

,count,mean,std,min,30%,50%,60%,90%,max
출장기간,6.0,4.666667,1.032796,3.0,4.5,5.0,5.0,5.5,6.0
교통비,6.0,3833.333333,1834.847859,1000.0,3000.0,4000.0,5000.0,5500.0,6000.0
식비,6.0,3500.000000,1760.681686,1000.0,3000.0,3000.0,3000.0,5500.0,6000.0
숙박비,6.0,2500.000000,1870.828693,1000.0,1500.0,2000.0,2000.0,4500.0,6000.0
부대비용,6.0,350.000000,187.082869,100.0,250.0,350.0,400.0,550.0,600.0

In [32]:
# 숫자 타입은 '산술 연산', 문자열 타입은 '문자열 결합'이 이루어 집니다.
payment.sum().to_frame().T

,사원명,출장지역,출장기간,부서,성별,교통비,식비,숙박비,부대비용
0,강찬혁이성진이순철신유석선진희유지혜,부산대구부산대구서울대구,28,영업부구매부전산부영업부총무부전산부,남자남자남자여자여자여자,23000,21000,15000,2100

In [33]:
payment.sum(numeric_only=True).to_frame().T

   출장기간    교통비     식비    숙박비  부대비용
0    28  23000  21000  15000  2100

In [34]:
payment.mean(numeric_only=True).to_frame().T

       출장기간          교통비      식비     숙박비   부대비용
0  4.666667  3833.333333  3500.0  2500.0  350.0

In [35]:
payment.min().to_frame().T

   사원명 출장지역 출장기간   부서  성별   교통비    식비   숙박비 부대비용
0  강찬혁   대구    3  구매부  남자  1000  1000  1000  100

<h2><font color="red">메소드 Chaining 연산 및 축 지정</font></h2>

<h4><font color="green">누락 데이터, 산술 연산, 축지정 </font></h4>

<h6><font color="BlueViolet">누락 데이터 개수 파악</font></h6>

In [36]:
payment.isnull()

     사원명   출장지역   출장기간     부서     성별    교통비     식비    숙박비   부대비용
0  False  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False  False  False
5  False  False  False  False  False  False  False  False  False

In [37]:
payment.isnull().sum().to_frame().T

   사원명  출장지역  출장기간  부서  성별  교통비  식비  숙박비  부대비용
0    0     0     0   0   0    0   0    0     0

In [38]:
print('전체 결측치 개수 : ' + str(payment.isnull().sum().sum()))

전체 결측치 개수 : 0

<h6><font color="BlueViolet">산술 연산</font></h6>

In [39]:
# 다음 문장은 오류가 발생합니다.
#print(payment + 5)

In [40]:
payment.dtypes.to_frame().T

      사원명    출장지역   출장기간      부서      성별    교통비     식비    숙박비   부대비용
0  object  object  int64  object  object  int64  int64  int64  int64

In [41]:
likes = payment.filter(items=['출장기간', '교통비', '식비', '숙박비', '부대비용'])
likes

   출장기간   교통비    식비   숙박비  부대비용
0     3  3000  1000  1000   100
1     5  5000  6000  2000   200
2     4  6000  3000  3000   400
3     5  1000  5000  6000   600
4     6  5000  3000  1000   500
5     5  3000  3000  2000   300

In [42]:
result = likes + 10
result

   출장기간   교통비    식비   숙박비  부대비용
0    13  3010  1010  1010   110
1    15  5010  6010  2010   210
2    14  6010  3010  3010   410
3    15  1010  5010  6010   610
4    16  5010  3010  1010   510
5    15  3010  3010  2010   310

<h6><font color="BlueViolet">축(axis) 지정하기</font></h6>

In [43]:
likelyhood = pd.read_csv('./../data/likelyhood.csv')
likelyhood.head()

   muscle  height  grade  speech  book  travel  skin likelyhood
0    50.0      90   40.0    30.0    80    40.0    90          A
1    90.0      60   50.0     NaN    50    70.0    60          B
2     NaN      50   60.0    50.0    40     NaN    70          B
3     NaN      40    NaN    90.0    50    60.0    20          C
4    60.0      70   70.0    50.0    70    30.0    80          A

In [44]:
print(likelyhood.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   muscle      12 non-null     float64
 1   height      14 non-null     int64
 2   grade       13 non-null     float64
 3   speech      13 non-null     float64
 4   book        14 non-null     int64
 5   travel      13 non-null     float64
 6   skin        14 non-null     int64
 7   likelyhood  14 non-null     object
dtypes: float64(4), int64(3), object(1)
memory usage: 1.0+ KB
None

In [45]:
likelyhood.count().to_frame().T

   muscle  height  grade  speech  book  travel  skin  likelyhood
0      12      14     13      13    14      13    14          14

In [46]:
likelyhood.count(axis=0).to_frame().T

   muscle  height  grade  speech  book  travel  skin  likelyhood
0      12      14     13      13    14      13    14          14

In [47]:
likelyhood.count(axis='rows').to_frame().T

   muscle  height  grade  speech  book  travel  skin  likelyhood
0      12      14     13      13    14      13    14          14

In [48]:
print('열 개수 : ' + str(len(likelyhood.columns)))

열 개수 : 8

In [49]:
likelyhood.count(axis='columns').head().to_frame().T

   0  1  2  3  4
0  8  7  6  6  8

In [50]:
likelyhood.sum(axis='columns', numeric_only=True).head().to_frame().T

       0      1      2      3      4
0  420.0  380.0  270.0  260.0  430.0

<h2><font color="red">기타 유용한 기능</font></h2>

<h4><font color="green">메모리 사용량</font></h4>

<h6><font color="BlueViolet">데이터 유형 확인</font></h6>

In [51]:
payment = pd.read_csv('./../data/payment02.csv', encoding='CP949')
payment

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
0  강찬혁   부산     3  영업부  남자  3000  1000  1000   100
1  이성진   대구     5  구매부  남자  5000  6000  2000   200
2  이순철   부산     4  전산부  남자  6000  3000  3000   400
3  신유석   대구     5  영업부  여자  1000  5000  6000   600
4  선진희   서울     6  총무부  여자  5000  3000  1000   500
5  유지혜   대구     5  전산부  여자  3000  3000  2000   300

<h6><font color="BlueViolet">상위 x명 추출</font></h6>

In [52]:
top=4
print('\'부대 비용\' 상위 '+ str(top) + '명 추출하기')
payment.nlargest(top, '부대비용')

'부대 비용' 상위 4명 추출하기

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
3  신유석   대구     5  영업부  여자  1000  5000  6000   600
4  선진희   서울     6  총무부  여자  5000  3000  1000   500
2  이순철   부산     4  전산부  남자  6000  3000  3000   400
5  유지혜   대구     5  전산부  여자  3000  3000  2000   300

<h6><font color="BlueViolet">상위 x명 중에서 하위 y명 추출</font></h6>

In [53]:
bottom=2
print('\'부대 비용\' 상위 '+ str(top) + '명 중에서 \'숙박비\' 하위 ' + \
      str(bottom) + '명 추출하기')
payment.nlargest(top, '부대비용').nsmallest(bottom, '숙박비')

'부대 비용' 상위 4명 중에서 '숙박비' 하위 2명 추출하기

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
4  선진희   서울     6  총무부  여자  5000  3000  1000   500
5  유지혜   대구     5  전산부  여자  3000  3000  2000   300

<h4><font color="green">query() 메소드 사용</font></h4>

<h6><font color="BlueViolet">관계 연산자 사용</font></h6>

In [54]:
payment.query('숙박비 > 식비')

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
3  신유석   대구     5  영업부  여자  1000  5000  6000   600

In [55]:
payment[payment['숙박비'] > payment['식비']]

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
3  신유석   대구     5  영업부  여자  1000  5000  6000   600

In [56]:
payment.query('교통비 == 식비')

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
5  유지혜   대구     5  전산부  여자  3000  3000  2000   300

In [57]:
payment[payment['교통비'] == payment['식비']]

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
5  유지혜   대구     5  전산부  여자  3000  3000  2000   300

<h6><font color="BlueViolet">조건식 필터링</font></h6>

In [58]:
# 조회하고자 하는 부서 목록
dept_col = ['영업부', '전산부', '구매부']
# 조회하고자 하는 컬럼 목록
column_list = ['사원명', '출장지역', '부서', '성별', '교통비']

# 부서가 dept_col에 포함되어 있고, 남자이며, 교통비가 4000이상 7000이하인 데이터
# @ 기호는 치환 변수의 의미로 사용됩니다.
sql = "부서 in @dept_col and 성별 == '남자' and 4000 <= 교통비 <= 7000" # 검색 조건
resultSet = payment.query(sql)
resultSet[column_list]

   사원명 출장지역   부서  성별   교통비
1  이성진   대구  구매부  남자  5000
2  이순철   부산  전산부  남자  6000

<h6><font color="BlueViolet">빈도수가 높은 상위 부서 2개 고르기</font></h6>

In [59]:
dept_frequency=payment.부서.value_counts()
print('부서별 빈도수 확인')
dept_frequency.to_frame().T

부서별 빈도수 확인

부서     영업부  전산부  구매부  총무부
count    2    2    1    1

In [60]:
rowsu=2 # 추출할 상위 개수
concern_data = dept_frequency.index[:rowsu].tolist()
concern_data

['영업부', '전산부']

In [61]:
# 빈도수 상위 2개 부서 멤버가 아닌 사원 중 남자인 사원은?
print('\n빈도 수가 많은 상위 ' + str(rowsu) + '개 : '+ str(concern_data))
filtering = payment.query("부서 not in @concern_data and 성별 == '남자'")
filtering

빈도 수가 많은 상위 2개 : ['영업부', '전산부']

   사원명 출장지역  출장기간   부서  성별   교통비    식비   숙박비  부대비용
1  이성진   대구     5  구매부  남자  5000  6000  2000   200